django_poll/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # "127.0.0.1:8000/polls/" 이후의 URL은 polls/urls.py가 handling
    path('polls/', include('polls.urls')),
]

django_poll/polls/urls.py
from django.urls import path
from . import views # 같은 폴더 내의 views.py를 import 

app_name = 'polls'

urlpatterns = [
    # "127.0.0.1:8000/polls/" 이후의 URL은 polls/urls.py가 handling하도록 만들 예정
    path('', views.index, name='index'), # '127.0.0.1:8000/polls/' 를 받아내도록 만들어줌

    # ~/polls/5/
    path('<int:question_id>/', views.detail, name='detail'),

    # ~/polls/5/vote
    path('<int:question_id>/vote', views.vote, name='vote'),

    # ~/polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
]

django_poll/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model): # DB Table for 설문조사 주제
    question_text = models.CharField(max_length=200) # 설문조사 주제 텍스트
    pub_date = models.DateTimeField('date published') # ‘date published’ : 관리자 페이지에서 보여질 항목명

    # Shell이나 관리자 페이지 등에서 DB Table 내의 데이터를 꺼냈을 때 보여지는 텍스트를 지정합니다.
    def __str__(self):
        return self.question_text

    # 현재 기준으로 하루 전 시점보다 더 이후에 등록된 Question인지 여부를 확인해주는 함수(True/False)
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
    
    was_published_recently.boolean = True
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.short_description = 'Published recently?'
    
class Choice(models.Model): # DB Table for 설문조사 주제별 선택지 (+ 선택지마다의 득표 수)
    # 자동으로 Question table의 Primary key를 Foreign Key로 세팅
    # on_delete=models.CASCADE : Question(질문) 항목 삭제 시 관계된 선택지들도 모두 자동 삭제
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # 설문조사 주제의 id 값
    choice_text = models.CharField(max_length=200) # 설문조사 주제에 대한 선택지 텍스트
    votes = models.IntegerField(default=0) # 해당 선택지의 득표 수
    
    def __str__(self):
        return self.choice_text

django_poll/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question

# Create your views here.
def index(request):
    # Question.objects.all()
    # id 오름차순, -id 내림차순
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    
    context = {'latest_question_list':latest_question_list}

    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    
    # try: 
    # q = Question.objects.get(id=question_id)
    # except Question.DoesNotExist:
    # raise Http404('Question {} does not exist.'.format(question_id))

    q = get_object_or_404(Question, id=question_id)

    return render(request, 'polls/detail.html', {'question' : q})
    

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # print(request.POST)
    # return HttpResponse('vote')
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice_select'])
        # request.POST['choice_select'] :
        # detail.html의 <input type="radio" name="choice_select" value="{{ choice.id }}">에서 날라온 값
        # form으로 제출된 POST Request 전체에서 'choice_select'가 name인 HTML 태그의 value를 꺼내는 코드
        # request.POST 는 {~~~, 'choice_select':7} 와 같은 dictionary 형태
    except:
        # request.POST['choice_select']값이 없을 경우, error_message를 가지고 details.html로 되돌아감
        context = {'question': question, 'error_message': "You didn't select a choice."}
        return render(request, 'polls/detail.html', context)
    else: # try 문에서 에러가 발생하지 않았을 경우 마지막에 실행됩니다.
        selected_choice.votes += 1
        selected_choice.save() # 실제 DB 저장
        return redirect('polls:results', question_id=question.id)


def results(request, question_id):

    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/result.html', {'question':question})

django_poll/polls/templates/polls/base.html
<!DOCTYPE html>

{% load static %}

<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Django Polls (version 1.0)</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link href="//fonts.googleapis.com/css?family=Do+Hyeon|Noto+Sans&display=swap" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    </head>

    <body>
        <div class="container">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <span class="navbar-brand">Django Polls (version 1.0)</span>
                </div>
                <ul class="nav navbar-nav">          
                  <li><a href = "{% url 'polls:index' %}">Voting</a></li>
                  <li class="navbar-right"><a href = "{% url 'admin:index' %}">Administrator</a></li>
                </ul>
              </div>
            </nav>
        <div>
              {% block content %}
              {% endblock %}
            </div>
          </div>
          <footer class="footer">
            <div class="container">
              <p class="text-muted">Copyright ⓒ 2021 Replus | Django Polls | All Rights Reserved</p>
            </div>
          </footer>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
          <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>        
    </body>
</html>

django_poll/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}

<html>
    <head>
    </head>
    <body>

        <h2>
            {{ question.question_text }}
        </h2>
        
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form action= "{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}

            <!--
                <input type='hidden' name='dev_passthrough' value="{{ question.id }}"> 
            -->
            
            {% for choice in question.choice_set.all %}
                <input type='radio' name='choice_select' id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for = "choice{{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label>
                <br>
            {% endfor %}

            <input type="submit" value="Vote">
        </form>
    </body>
</html>

{% endblock %}

django_poll/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}

{% if latest_question_list %}
    <ui>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question_id=question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ui>

    {% else %}
        <p>No polls are available.</p>

{% endif %}

{% endblock %}

django_poll/polls/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>
    {{ question.question_text }}
</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} got voted for {{ choice.votes }} times.</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question_id=question.id %}">
    Vote again?
</a>

{% endblock %}